Add documentation on instructions module for Bootcamp website
gem5bootcamp/gem5-bootcamp-env pull request #30
Opened 2022-08-15 18:20 UTC by aakahlow

2022-08-15 23:05 UTC, BobbyRBruce requested changes
This is really good. Just fix up the links and i'll approve it.

2022-08-15 23:05 UTC, BobbyRBruce commented on modules/Developing gem5 models/_posts/2000-07-01-instructions.md
> +![ROp format used by R format instructions](../../../assets/img/ROpFormat.png)
Fix link

2022-08-15 23:05 UTC, BobbyRBruce commented on modules/Developing gem5 models/_posts/2000-07-01-instructions.md
> +![Example of BasicDeclare template](../../../assets/img/BasicDeclare.png)
Fix link

2022-08-15 23:05 UTC, BobbyRBruce commented on modules/Developing gem5 models/_posts/2000-07-01-instructions.md
> +![Example of BasicExecute template](../../../assets/img/ExecuteTemplate.png)
Fix link

2022-08-17 21:21 UTC, aakahlow commented on modules/Developing gem5 models/_posts/2000-07-01-instructions.md
> +![ISA dependent and independent components of gem5](../../../assets/img/ISAInd.png)
Done

2022-08-17 21:22 UTC, aakahlow commented on modules/Developing gem5 models/_posts/2000-07-01-instructions.md
> +![High level flow of instruction definition in gem5](../../../assets/img/ISAParser.png)
fixed

2022-08-17 21:22 UTC, aakahlow commented on modules/Developing gem5 models/_posts/2000-07-01-instructions.md
> +![Decode block in gem5 ISA DSL](../../../assets/img/decode.png)
fixed

2022-08-17 21:22 UTC, aakahlow commented on modules/Developing gem5 models/_posts/2000-07-01-instructions.md
> +![ROp format used by R format instructions](../../../assets/img/ROpFormat.png)
fixed

2022-08-17 21:22 UTC, aakahlow commented on modules/Developing gem5 models/_posts/2000-07-01-instructions.md
> +![Example of BasicDeclare template](../../../assets/img/BasicDeclare.png)
fixed

2022-08-17 21:22 UTC, aakahlow commented on modules/Developing gem5 models/_posts/2000-07-01-instructions.md
> +![Example of BasicExecute template](../../../assets/img/ExecuteTemplate.png)
fixed

2022-08-22 17:49 UTC, BobbyRBruce approved these changes

2022-08-22 21:26 UTC, merged